### ISSUE TITLE
License

### ISSUE THREAD

**Issue by adriaangraas** [nikitinvv/rectv_gpu#1]
Hi,

I would like to use your code to try the foam data that is deposited in the TomoBank.
Can you provide a license to your code? Without doing so, formally I cannot use your code.
See also [adding a license to a repository](https://help.github.com/articles/adding-a-license-to-a-repository/) and [No License](https://choosealicense.com/no-permission/).

Best regards, Adriaan

**Comment by nikitinvv** [comment]
Hello Adriaan,

I have created a BSD-2 license file. Thanks for your message.

Viktor

**Comment by adriaangraas** [comment]
Thank you for the prompt reply!

Adriaan
